[package]
name = "github-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
jsonwebtoken = "8.2.0"
reqwest = "0.11.13"
serde = "1.0.152"
